services:
  postsapi:
    build: 
        context: .
        dockerfile: PostsAPI/Dockerfile
    container_name: posts-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  testclient:
    build: ./TestClient
    depends_on:
      postsapi:
        condition: service_healthy
    environment:
      - API_BASE_URL=http://postsapi:8080