services:
  posts-api:
    build: 
        context: .
        dockerfile: PostsAPI/Dockerfile
    container_name: posts-api
    ports:
      - "5000:5000"  # External access via localhost:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  test-client:
    build: 
        context: .
        dockerfile: TestClient/Dockerfile
    container_name: test-client
    environment:
      - API_BASE_URL=http://posts-api:5000
    depends_on:
        posts-api:
            condition: service_healthy
    networks:
        - app-network
    

networks:
  app-network:
    driver: bridge