services:
  posts-api:
    build: 
        context: .
        dockerfile: PostsAPI/Dockerfile
    container_name: posts-api
    ports:
      - "5000:8080"  # External access via localhost:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  test-client:
    build: 
        context: .
        dockerfile: TestClient/Dockerfile
    container_name: test-client
    environment:
      - API_BASE_URL=http://posts-api:8080
    depends_on:
        posts-api:
            condition: service_healthy
    networks:
        - app-network
    

networks:
  app-network:
    driver: bridge